Repository fga-eps-mds/2019.2-Amika-Frontend, pull requests merged in 2019-10, with the labels that each got.

#25 Criando código de conduta
  CODE_OF_CONDUCT.md
Labels: EPS, documentation, duplicate

#24 Criando licença do projeto
  LICENSE
Labels: EPS, MDS, documentation, duplicate

#26 Criando guia de contribuição
  CONTRIBUTING.md
Labels: EPS, documentation, duplicate

#23 [DOC19] Atualizando README do Frontend
  README.md
Labels: EPS, documentation, enhancement

#47 issue46 refatorar o template de requisitar funcionalidade.
  .github/ISSUE_TEMPLATE/requisitar-funcionalidade.md
Labels: documentation, easy to solve, good first issue

#56 Alterando versões das bibliotecas
  package-lock.json
  package.json
Labels: bug, easy to solve

#60 Corrige Dockerfile
  Dockerfile
  docker-compose.yml
Labels: DevOps, bug

#62 Criando o template das issues de refatoramento
  .github/ISSUE_TEMPLATE/requisitar-refatoramento.md
Labels: documentation, refactoring

#57 US18 - Área Informativa
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/area-informativa/area-informativa.component.css
  src/app/area-informativa/area-informativa.component.html
  src/app/area-informativa/area-informativa.component.spec.ts
  src/app/area-informativa/area-informativa.component.ts
  src/app/homepage/homepage.component.html
Labels: MDS, User Story

#71 Resolvendo bug do tipo do atributo data no humor
  src/app/humor/humor.component.ts
  src/app/humor/humor.model.ts
Labels: EPS, bug, easy to solve

#79 [Hotfix] Consertando bug do ng build
  src/app/app.component.ts
Labels: bug
