Repository fga-eps-mds/2019.2-Amika-Frontend, pull requests merged in 2019-11, with the labels that each got.

#86 Issue 76 refatorar tela turma
  src/app/app.component.css
  src/app/app.module.ts
  src/app/turmas/turma-edit/turma-edit.component.css
  src/app/turmas/turma-edit/turma-edit.component.html
  src/app/turmas/turmas-create-dialogo.css
  src/app/turmas/turmas-create-dialogo.html
  src/app/turmas/turmas.component.css
  src/app/turmas/turmas.component.html
  src/app/turmas/turmas.component.ts
  src/styles.css
Labels: enhancement, refactoring

#89 [HOT-FIX] Adiciona JWT no header de autorização
  src/app/autenticacao.service.ts
Labels: bug

#91 [HOT-FIX] Corrige URN do perfil de aluno
  src/app/perfil-usuario/perfil-usuario.service.ts
Labels: bug

#97 [HOT-FIX] Corrige sincronização de deployments
  angular.json
  package.json
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/environments/environment.stg.ts
Labels: DevOps, bug

#85 Criação da página do erro 404 - página não encontrada.
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/page-not-found/page-not-found.component.css
  src/app/page-not-found/page-not-found.component.html
  src/app/page-not-found/page-not-found.component.spec.ts
  src/app/page-not-found/page-not-found.component.ts
Labels: easy to solve

#87 Issue 54 - Adicionar spinner para carregamento de páginas
  src/app/app.component.ts
  src/app/app.module.ts
  src/index.html
  src/styles.css
Labels: easy to solve, enhancement

#101 Conserto do WARNING no styles.css
  src/styles.css
Labels: bug

#99 Issue 67 - Adicionar ícones com a logo da aplicação
  src/assets/icons/favicon.png
  src/assets/icons/icon-128x128.png
  src/assets/icons/icon-144x144.png
  src/assets/icons/icon-152x152.png
  src/assets/icons/icon-192x192.png
  src/assets/icons/icon-384x384.png
  src/assets/icons/icon-512x512.png
  src/assets/icons/icon-72x72.png
  src/assets/icons/icon-96x96.png
  src/favicon.ico
  src/index.html
Labels: easy to solve, enhancement

#100 Issue 77 Refatorar humor
  src/app/humor/humor.component.css
  src/app/humor/humor.component.html
  src/app/humor/humor.service.ts
Labels: enhancement, refactoring

#108 Issue 93 refatorar grupos
  src/app/app.component.html
  src/app/app.module.ts
  src/app/grupos/grupo-edit/grupo-edit.component.css
  src/app/grupos/grupo-edit/grupo-edit.component.html
  src/app/grupos/grupos-create-dialogo.css
  src/app/grupos/grupos-create-dialogo.html
  src/app/grupos/grupos.component.css
  src/app/grupos/grupos.component.html
  src/app/grupos/grupos.component.ts
  src/app/turmas/turma-edit/turma-edit.component.html
  src/app/turmas/turmas.component.css
  src/app/turmas/turmas.component.html
  src/assets/icons/group.png
  src/assets/icons/random.png
  src/assets/icons/shuffle.png
Labels: enhancement, refactoring

#113 Renomeando titulos das paginas
  src/app/app.component.html
Labels: easy to solve, refactoring

#119 [AMB12] Configurando ambiente de testes e criando testes de turmas
  .dockerignore
  .travis.yml
  Dockerfile.test
  angular.json
  docker-compose-tests.yml
  karma.conf.js
  package-lock.json
  package.json
  src/app/agendas/agenda-edit/agenda-edit.component.spec.ts
  src/app/agendas/agenda.service.spec.ts
  src/app/agendas/agendas.component.spec.ts
  src/app/aluno-auto-registro/aluno-auto-registro.component.spec.ts
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/area-informativa/area-informativa.component.spec.ts
  src/app/grafico-humor/grafico-humor.component.spec.ts
  src/app/grupos/grupo-edit/grupo-edit.component.spec.ts
  src/app/grupos/grupo.service.spec.ts
  src/app/grupos/grupos.component.spec.ts
  src/app/homepage/homepage.component.spec.ts
  src/app/humor/humor.component.spec.ts
  src/app/lista-de-matricula/lista-de-matricula.component.spec.ts
  src/app/login/login.component.spec.ts
  src/app/matriculas/shared/matricula-individual.spec.ts
  src/app/matriculas/shared/matricula.spec.ts
  src/app/page-not-found/page-not-found.component.spec.ts
  src/app/perfil-usuario/perfil-usuario.component.spec.ts
  src/app/turmas/turma-edit/turma-edit.component.spec.ts
  src/app/turmas/turma.service.spec.ts
  src/app/turmas/turma.service.ts
  src/app/turmas/turmas.component.spec.ts
  src/app/turmas/turmas.component.ts
  src/app/turmas/turmas.model.ts
  src/app/turmas/turmas.service.spec.ts
Labels: enhancement

#131 [HOT-FIX] Issue 130 Badges Testes
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: bug

#134 Ajustando posicao do botao de adicionar no mobile
  src/app/agendas/agendas.component.css
  src/app/agendas/agendas.component.html
  src/app/grupos/grupos.component.css
  src/app/turmas/turmas.component.css
Labels: easy to solve, refactoring

#121 US19 - manter materiais
  src/app/app.module.ts
Labels: MDS, User Story

#146 Issue 145 Corrigindo bugs do Heroku
  src/app/agendas/agenda-edit/agenda-edit.component.html
  src/app/agendas/agenda-edit/agenda-edit.component.ts
  src/app/agendas/agenda.service.ts
  src/app/agendas/agendas-create-dialogo.html
  src/app/agendas/agendas.component.html
  src/app/agendas/agendas.component.ts
  src/app/grafico-humor/grafico-humor.component.ts
  src/app/grupos/grupo-edit/grupo-edit.component.html
  src/app/grupos/grupos.component.html
  src/app/lista-de-matricula/lista-de-matricula.component.html
  src/app/lista-de-matricula/lista-de-matricula.component.ts
  src/app/login/login.component.html
  src/app/turmas/turma-edit/turma-edit.component.html
  src/app/turmas/turmas.component.html
Labels: bug

#151 Adicionadas as fotos dos alunos na aba de grupos do professor.
  src/app/grupos/grupos.component.css
  src/app/grupos/grupos.component.html
  src/app/grupos/grupos.component.ts
Labels: MDS, easy to solve, enhancement

#161 [HOTFIX] Removendo abertura da sidebar ao clicar na logo
  src/app/app.component.html
Labels: bug, easy to solve

#162 [HOTFIX] Consertando bug de agendas
  src/app/agendas/agendas.component.css
Labels: bug, easy to solve

#159 Issue 158 Adicionando tela de visualizar materiais
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/grupo/grupo.component.css
  src/app/grupo/grupo.component.html
  src/app/visualizar-materiais/visualizar-materiais.component.css
  src/app/visualizar-materiais/visualizar-materiais.component.html
  src/app/visualizar-materiais/visualizar-materiais.component.spec.ts
  src/app/visualizar-materiais/visualizar-materiais.component.ts
Labels: enhancement

#149 Criando alertas de erros e sucessos
  package-lock.json
  package.json
  src/app/agendas/agenda-edit/agenda-edit.component.ts
  src/app/agendas/agendas.component.ts
  src/app/alerta.service.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/grupos/grupo-edit/grupo-edit.component.ts
  src/app/grupos/grupos.component.ts
  src/app/humor/humor.component.ts
  src/app/lista-de-matricula/lista-de-matricula.component.ts
  src/app/materiais/materiais.component.ts
  src/app/turmas/turma-edit/turma-edit.component.ts
  src/app/turmas/turmas.component.ts
Labels: enhancement, refactoring

#164 [HOTFIX] Corrigindo bug na chamada de um método inexistente
  src/app/humor/humor.component.html
Labels: bug

#167 [HOTFIX] Padronizando tamanho das imagens em grupo
  src/app/grupo/grupo.component.html
Labels: bug, easy to solve

#172 Adicionando mensagem de validacao ao registrar
  src/app/requisicao.service.ts
Labels: enhancement, refactoring

#155 US12 Realizar Agendas da Felicidade
  src/app/agendas-realizadas/agendas-realizadas-dialog/agendas-realizadas-dialog.component.css
  src/app/agendas-realizadas/agendas-realizadas-dialog/agendas-realizadas-dialog.component.html
  src/app/agendas-realizadas/agendas-realizadas-dialog/agendas-realizadas-dialog.component.ts
  src/app/agendas-realizadas/agendas-realizadas.component.css
  src/app/agendas-realizadas/agendas-realizadas.component.html
  src/app/agendas-realizadas/agendas-realizadas.component.ts
  src/app/agendas-realizadas/agendas-realizadas.model.ts
  src/app/agendas-realizadas/agendas-realizadas.service.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/lista-de-matricula/lista-de-matricula.component.html
  src/app/lista-de-matricula/lista-de-matricula.component.ts
Labels: User Story, enhancement

#173 [HOTFIX] Consertando erro heroku
  src/app/agendas-realizadas/agendas-realizadas.component.ts
Labels: bug

#175 [HOTFIX] Corrigindo erro do heroku
  src/app/app-routing.module.ts
Labels: bug

#177 Alterando rota do botao de agendas da navbar do aluno
  src/app/app.component.html
Labels: easy to solve, refactoring
